---
# Имя хоста для логов/комментариев в шаблонах.
inventory_hostname_label: vpn2

# Публичный endpoint, используемый клиентами OVPN/WG. По умолчанию равен ansible_host.
server_public_ip: "{{ ansible_host }}"

# Имя WAN-интерфейса. Если пусто — определится автоматически (роль common).
#wan_iface: eth0

# Public key WG-сервера (известно из `wg show wg0 public-key`).
# Используется только для выдачи новым WG-клиентам — НЕ как источник правды.
# Реальная истина — приватник в /etc/wireguard/server.key на сервере.
wg_server_pubkey: L+F3LDK6IKZyFcHG8o5cLbi4TuM+5Blr7dmzGs0C30k=

# Public key wg1-сервера (WDTT-туннель). Используется add-wdtt-peer.yml
# для генерации клиентских конфигов.
wdtt_wg_server_pub: 029Do1cME3DerDVIm1kU9/E1cNeSDBKwR/dZdqOnmg0=
