---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart sing-box
  ansible.builtin.systemd:
    name: "{{ sb_unit }}"
    state: restarted

- name: restart sing-box-refresh timer
  ansible.builtin.systemd:
    name: "{{ sb_refresh_unit }}.timer"
    state: restarted
    enabled: true
  when: not ansible_check_mode
